name: My Workflow File
on:
  push:
    branches: [main]

jobs: 
  builds:
  # create vm with ubuntu OS
    runs-on: ubuntu-20.04

    steps:
    - name: greeting steps
      run: |
        echo "Hello World"
        
    - name: Checkout my codes
      uses: actions/checkout@v4
    - name: print content
      run:  |
        ls
        
      
    
