name: My Workflow File
on:
  push:
    branches: [main]

jobs: 
  builds:
  # create vm with ubuntu OS
    runs-on: Ubuntu- 20.04

    steps:
    - name: greeting steps
      run: |
        echo "Hello World"
    
